---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ovsdbdockerfile"
  namespace: "default"
  labels:
    app: "ovsdbdockerfile"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ovsdbdockerfile"
  template:
    metadata:
      labels:
        app: "ovsdbdockerfile"
    spec:
      containers:
      - name: "ovsdbdokerfile-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/lakshmidevi521/ovsdbdokerfile@sha256:0f6fa4765f4512470eff425900218caf66ef7386d9da2194ed160d1935babd1e"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ovsdbdockerfile-hpa-wtig"
  namespace: "default"
  labels:
    app: "ovsdbdockerfile"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ovsdbdockerfile"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

